### ISSUE TITLE
Clock is great - a "Timer" Solution would be even greater

### ISSUE THREAD

**Issue by RStadlmair** [jdhitsolutions/PSClock#3]
Hi Jeffrey ! 
Love PSClock - Any chance this gets a countdown timer ?
Cheers / R.

**Comment by jdhitsolutions** [comment]
I have a module called [PSTimers](https://github.com/jdhitsolutions/PSTimers) that has a few countdown timers. But I don't think I have anything like a WPF timer.  I suppose it wouldn't be too hard to implement. I'd most likely put it in the PSTimers module with other timer-related commands.

**Comment by RStadlmair** [comment]
I would find this pretty useful, for presentations, videos or live-demos so that people know when it starts.

**Comment by jdhitsolutions** [comment]
Closing the issue here. I've merged this with a long-standing issue I already had open in the PSTimers module. https://github.com/jdhitsolutions/PSTimers/issues/1

**Comment by jdhitsolutions** [comment]
I've added `Start-PSCountdownTimer` to the[ PSTimers module.](https://github.com/jdhitsolutions/pstimers)
